print("Here is the headmaster of Hogwarts School of Witchcraft and Wizardry!")
print("Professor Albus Dumbledore")
print("He is known for his wisdom and powerful magic.")
print("He has guided many young witches and wizards on their magical journeys.")
print("May his teachings inspire you on your own magical path!")

print("here is the potion master of Hogwarts School of Witchcraft and Wizardry!")
print("Professor Severus Snape")
print("He is known for his expertise in potion-making and his strict demeanor.")
print("He has a complex history and plays a crucial role in the fight against dark magic.")
print("May his knowledge of potions aid you in your magical studies!")

print("Here is the Defense Against the Dark Arts professor of Hogwarts School of Witchcraft and Wizardry!")
print("Professor Minerva McGonagall")
print("She is known for her strict but fair teaching style and her ability to transform into a cat.")
print("She is a skilled witch and a loyal member of the Order of the Phoenix.")
print("May her dedication to protecting students inspire you in your magical journey!")

print("Here is the Care of Magical Creatures professor of Hogwarts School of Witchcraft and Wizardry!")
print("Professor Rubeus Hagrid")
print("He is known for his love of magical creatures and his gentle giant personality.")
print("He has a deep connection with the magical world and often introduces students to fascinating creatures.")
print("May his passion for magical creatures ignite your own curiosity and care for the magical world!")
print("let's get you sorted into a house!")